spring:
  application:
    name: rjournal
  datasource:
    url: jdbc:h2:mem:rjournaldb
    driver-class-name: org.h2.Driver
    username: username
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true
logging:
    level:
        org:
            springframework:
                security: DEBUG
                web: DEBUG